### ISSUE TITLE
Matching properties with reserved names

### ISSUE THREAD

**Issue by chrismytton** [lloyd/JSONSelect#17]
I am testing JSONSelect against some [activity streams](http://activitystrea.ms/specs/json/1.0/#examples) json. The activity streams specification defines an `object` property in the json. 

When I try to match the selector `.object .objectType` I am getting `string required after .`.

It seems that `object` is a reserved word for type selectors. I'm hoping a change to [this](https://github.com/lloyd/JSONSelect/blob/669b66ccdbfb6bcc10a11852d15abcbbf503bd74/src/jsonselect.js#L50) regular expression will solve the problem, but I'm not sure what?

**Comment by lloyd** [comment]
You may use quotes around property names to both force them to be interpreted as strings and to include chars like spaces and control chars that are allowable by the json spec:

```
."object" .objectType
```

Going to leave this open though, it seems like the js parser could disambiguate given context.

**Comment by chrismytton** [comment]
Awesome! Thanks for the quick response.

Also worth noting that it seems that the same error occurs when the reserved name is used as _part_ of the property name, so your example would have to be written as:

``` css
."object" ."objectType"
```

**Comment by chrismytton** [comment]
Actually I'm getting `invalid json string` when using the above selector? Not sure if that is related to the previous issue though?

This selector also gives the same error:

``` css
."name" ."first"
```

**Comment by lloyd** [comment]
oh, that's no good.  I'll add a test or two and check it out...
