### ISSUE TITLE
Can not use multiple val selectors with strings

### ISSUE THREAD

**Issue by kpdecker** [lloyd/JSONSelect#21]
Attempting to do something like 

```
:has(:root > :first-child:val("string")) :has(:root > :first-child:val("string"))
```

Causes an invalid json string error.

Ran this with some additional logging and it appears that the parser is trying to evaluate this as a JSON string:

```
"string")) :has(:root > :first-child:val("string"
```

Can work around this issue by performing another evaluation loop in the javascript space.

**Comment by lloyd** [comment]
nice find, I'll take a look shortly.
