### ISSUE TITLE
match exact path

### ISSUE THREAD

**Issue by gitfy** [lloyd/JSONSelect#22]
Hi,
First of all, it is great utility and i was able to find a good use in my project.

one thing which i came across was, when i do 

JSONSelect.match(path , obj), it return me all the sub object which matches the path at all levels. What i mean by that is

let us say :
{
   "attribute1" : value1,
   "subObject" : {
       "attribute1" : value2
   }
}

JSONSelect(".attribute1" , obj) will return me an array
[ "attribute1" : value1 , "attribute1" , "value2 ]

Is there a way to say, i want the exact match (like first level) and not any sub-levels......

any advise is appreciated.

Thanks.

**Comment by lloyd** [comment]
Hi @gitfy!

Yeah, what you want is the `:root` pseudo element.  You can match only the top level with something like this:

```
:root > .attribute1
```

Search for "_:root_" in my [recent blog post](http://trickyco.de/jsonselect-grows-up) about JSONSelect for more discussion about the :root pseudo element!

**Comment by gitfy** [comment]
Thanks. that works.
