### ISSUE TITLE
Select single value, not an array

### ISSUE THREAD

**Issue by caseycrites** [lloyd/JSONSelect#23]
I've been trying to get this to work for a bit now and can't seem to figure it out.  What I'm trying to do is simply return a value instead of an array that contains a single value.  For example, given this json:

{this: "is", some: {test: "json"}}

and this JSONSelect query:

.some > .test

is there a way to get back simply "json", instead of ["json"]?  I know I can index the array when the result comes out, but I'd really prefer to be able to state in my JSONSelect query that I just want a value and not an array.

**Comment by lloyd** [comment]
what would you like match to do if there is more than one node that matches?

How about this, have a look at the source.  match is built upon foreach, so you can implement a new match function with whatever semantics you're after at a higher level.  for reference, here's the match implementation:

https://github.com/lloyd/JSONSelect/blob/master/src/jsonselect.js#L493-498
