### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by josegonzalez** [lloyd/JSONSelect#36]
See title.

**Comment by lloyd** [comment]
no way!  how can a specification, idea, and reference implementation die?  

you got issues that need love?

**Comment by josegonzalez** [comment]
Yes, all the issues that are open and the pull requests that remain unmerged ;)

**Comment by lloyd** [comment]
Roger.  I'll be a better maintainer in the coming week.  Sorry for sucking.

--lloyd

**Comment by josegonzalez** [comment]
You better, I know where you work.
