### ISSUE TITLE
Offer a minified version

### ISSUE THREAD

**Issue by RonnyO** [lloyd/JSONSelect#4]
Just a suggestion - Could be nice to have the .min.js version with the important comments intact right in the repo.

**Comment by lloyd** [comment]
maybe instead of putting this in-repo I'll autogen upon publish to jsonselect.org.  sound ok?

**Comment by RonnyO** [comment]
ok, but having this in-repo means people could hotlink the raw file from GitHub. Your call :-)

**Comment by paulirish** [comment]
hotlinking github files doesnt work for IE9+

also github doesnt like it. :)

**Comment by RonnyO** [comment]
Didn't know about that issue, interesting. I actually thought about hotlinking for things like jsFiddle, not production use. But then you don't need the minified version, so never mind :-P
