### ISSUE TITLE
node.js module

### ISSUE THREAD

**Issue by beriberikix** [lloyd/JSONSelect#6]
As far as I can tell, this could easily be made into a node.js module by replacing the JSON parser with the native method in node.

**Comment by tj** [comment]
should be optimized for node too, ditching some of the more expensive calls that are not needed

**Comment by tmpvar** [comment]
https://github.com/lloyd/JSONSelect/pull/7 -- support for node

**Comment by lloyd** [comment]
merged, more discussion in issue #7.
