### ISSUE TITLE
ie6 compatibility

### ISSUE THREAD

**Issue by paulirish** [lloyd/JSONSelect#9]
I know, it's a real jerk thing to ask for...

but I'd like to incorporate JSONSelect into the Modernizr test suite but it doesnt run in IE6 which is a dealbreaker for me.

Not exactly sure where it's choking.. :/

you think you could take a look?

**Comment by lloyd** [comment]
if you didn't bring it up, someone else woulda.  I'll take a peek in the next couple days.

**Comment by lloyd** [comment]
@rwldrn closed this as part of contributing a build system which integrates jshint!  The site will not look pretty, but the library works!
